services: 
  frontend:
    container_name: glorialan.com-frontend
    build:
      context: .
      dockerfile: ./docker/nextjs.Dockerfile
      target: runner
    restart: always #change if you don't want your container restarting
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    networks:
      - gloria-net

networks:
  gloria-net:
    name: gloria-net
    external: true