# A Github action script that automatically

name: Build & release Docker image
run-name: ${{ github.actor }} is star out GitHub Actions 🚀

on:
  # Allows us to manually trigger the action
  workflow_dispatch:
  # This action will automatically run on a push even to the production respository
  push:
    branches:
      - 'production'
env:
  DOCKER_IMAGE_NAME: glorialan.com-frontend
  DOCKER_REGISTRY_URL: junweiwang03

jobs:
  build_docker_images:
    # Job name that shows in the GitHub UI
    name: Build Docker Imagesdf
    # Runner to use
    runs-on: ubuntu-22.04
    # runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # - name: Get the release version
    #   # i.e.: release/1.0.0 -> 1.0.0
    #   id: strip-branch-name
    #   run: |
    #     release_version=$(echo "${{ github.ref }}" | sed 's/refs\/heads\/.*\///')
    #     echo "Building release version $release_version"
    #     echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV
    #     shell: bash

    # Build the Docker image
    - name: Build the Docker image
      # run: docker build . --file Dockerfile --tag $DOCKER_IMAGE_NAME:$RELEASE_VERSION
      run: docker build -f ./docker/nextjs.Dockerfile --platform linux/amd64 -t glorialan.com-frontend .
    # Tag the Docker Images
    - name: Tag the image for the private registry $DOCKER_REGISTRY_URL
      run: docker tag $DOCKER_IMAGE_NAME $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME

    - name: Create a latest image as well
      run: docker tag $DOCKER_IMAGE_NAME $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME:latest

    # Push the images to the registry
    - name: Push the Docker image with version number
      run: docker push $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME

    - name: Push the latest tag
      run: docker push $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME:latest

    # Remove the local images
    - name: Remove the Docker image with version number
      run: docker rmi $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME

    - name: Remove the local image
      run: docker rmi $DOCKER_IMAGE_NAME
